### ISSUE TITLE
npm start gives weird error 8

### ISSUE THREAD

**Issue by steverob** [backstopmedia/bleeding-edge-sample-app#50]
Hi guys

I was able to install packages with `npm install` but when I did `npm start`, this is what I got:

```
App started goto - http://0.0.0.0:8080

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: listen EADDRINUSE
    at errnoException (net.js:901:11)
    at Server._listen2 (net.js:1039:14)
    at listen (net.js:1061:10)
    at Server.listen (net.js:1135:5)
    at EventEmitter.app.listen (/home/steve/dev/js/react/bleeding-edge-sample-app/node_modules/express/lib/application.js:559:24)
    at Object.<anonymous> (/home/steve/dev/js/react/bleeding-edge-sample-app/server/server.js:33:9)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
npm ERR! weird error 8
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian

npm ERR! not ok code 0
```

btw:

```
$ which node
/usr/bin/node

$ which nodejs
/usr/bin/nodejs
```

I have `nodejs-legacy` also installed on my `Ubuntu 14.04` system.

**Comment by clock21am** [comment]
can you please exam the above bug in a simple tern

**Comment by Oyindrila2305** [comment]
I have the same issue weird error 8 but with below output :

SyntaxError: Unexpected token ILLEGAL
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:902:3
npm ERR! weird error 8

Can somebody help with it.
