### ISSUE TITLE
Is book and sample app still being maintained?

### ISSUE THREAD

**Issue by ghost** [backstopmedia/bleeding-edge-sample-app#56]
I purchased the book and tried out the sample app.  npm install emitted multiple errors.  Just wondering if the book and sample app are still being maintained.  Thanks.

**Comment by jingjlii** [comment]
+1

**Comment by sialvsic** [comment]
+1

**Comment by raiello** [comment]
I am also seeing lots of messages including this one regarding the license
npm WARN EPACKAGEJSON bleeding-edge-sample-app@0.0.1 license should be a valid SPDX license expression

**Comment by raiello** [comment]
and also 

npm start

> bleeding-edge-sample-app@0.0.1 prestart /Users/aiellor/_work/bleeding-edge-sample-app-master
> npm run-script build
> 
> bleeding-edge-sample-app@0.0.1 build /Users/aiellor/_work/bleeding-edge-sample-app-master
> browserify -t reactify client/client.js > public/build/bundle.js --debug
> 
> bleeding-edge-sample-app@0.0.1 start /Users/aiellor/_work/bleeding-edge-sample-app-master
> node server/server.js

App started goto - http://0.0.0.0:8080
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE :::8080
    at Object.exports._errnoException (util.js:855:11)
    at exports._exceptionWithHostPort (util.js:878:20)
    at Server._listen2 (net.js:1237:14)
    at listen (net.js:1273:10)
    at Server.listen (net.js:1369:5)
    at EventEmitter.listen (/Users/aiellor/_work/bleeding-edge-sample-app-master/node_modules/express/lib/application.js:617:24)
    at Object.<anonymous> (/Users/aiellor/_work/bleeding-edge-sample-app-master/server/server.js:33:9)
    at Module._compile (module.js:398:26)
    at Object.Module._extensions..js (module.js:405:10)
    at Module.load (module.js:344:32)

npm ERR! Darwin 14.5.0
npm ERR! argv "/usr/local/Cellar/node/5.3.0/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v5.3.0
npm ERR! npm  v3.3.12
npm ERR! code ELIFECYCLE
npm ERR! bleeding-edge-sample-app@0.0.1 start: `node server/server.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the bleeding-edge-sample-app@0.0.1 start script 'node server/server.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the bleeding-edge-sample-app package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node server/server.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls bleeding-edge-sample-app
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /../_work/bleeding-edge-sample-app-master/npm-debug.log
